version: '3.8'
services:
  backend:
    ports:
      - "80:80"
    volumes:
      - ./:/app

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: "8081"
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - postgres

  centrifugo:
    ports:
      - "8000:8000"
